### ISSUE TITLE
Constant Disconnect from socket.io

### ISSUE THREAD

**Issue by VrTech** [floatinghotpot/socket.io-unity#27]
![image](https://user-images.githubusercontent.com/19533090/39492058-57941e3a-4d5c-11e8-9b9c-fd2275997001.png)

Do you know why Unity keeps disconnect and connect to socket.io ? Thank you

**Comment by enGMzizo** [comment]
I found the same issue and it happens exactly every 30 seconds

**Comment by Zbluu** [comment]
I had the same issue.
It was an error in one of my custom events, so my Unity client was automatically disconnected.
Try to remove all your event listeners. And check also the pingTimeout and pingInterval on your server.

**Comment by maginc** [comment]
Same thing, it just keeps reconnecting even if everything is ok.

**Comment by kodypeterson** [comment]
I found that setting the `pingInterval` to 500 resolves this issue.

It looks like the Github project for the SocketIoClientDotNet test server does this as well https://github.com/Quobject/SocketIoClientDotNet/blob/f7e768793abfda7f4660d2f5b0260a325c0c2487/TestServer/server.js#L32

**Comment by maginc** [comment]
It's actually working! Thanks mate!

**Comment by ltphy** [comment]
Where can i set the pingInterval in my client (C#) script?

**Comment by Zbluu** [comment]
I think you can't, the pingInterval is defined by the server, not the client.

**Comment by jimtendo** [comment]
I was having a similar issue (different cause) and thought it might be worth posting here in case others stumble upon this.

I have a VueJS App that contained a link like so:

```
<a href="bitcoincash:qrks5vefcxzjrmadcn5e3vthkp65lh4npvd0gw3qcs">Pay</a>
```

Clicking this link would force my SocketIO client to disconnect (probably considered a "navigate away" by the Socket IO client library - suspect other URL schemes would behave the same).

To mitigate, just add `target="_blank"` to your hyperlink so that the hyperlink is opened in a new window (thus avoiding Socket IO considering this a "navigate away" action).

**Comment by astechnolabs-fullstack** [comment]
> I found that setting the `pingInterval` to 500 resolves this issue.
> 
> It looks like the Github project for the SocketIoClientDotNet test server does this as well https://github.com/Quobject/SocketIoClientDotNet/blob/f7e768793abfda7f4660d2f5b0260a325c0c2487/TestServer/server.js#L32

not working. I tried this with my Node code, same issue...
